name: 'Show disk usage'
description: 'Show information about disk usage'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        set -x
        df -h
        sudo ls -lRh /tmp/* || true
        sudo du -sh /tmp || true
        sudo du -sh /tmp/* || true
        sudo find /tmp/ -size +5M | sudo xargs ls -lh
        sudo du -sh ./* || true
        sudo find ./ -size +5M   | xargs ls -lh
        sudo du -sh /var/
        sudo du -sh /var/lib/docker/
        #sudo du -sh /home/runner/work/
        set +x
