build-env:
  build_only: true
  from:
    type: docker
    url: ${{STACKER_BUILD_BASE_IMAGE}}
  run: |
    # libapparmor is only in testing
    head -n1 /etc/apk/repositories | sed 's/main/testing/g' >> /etc/apk/repositories

    apk add git findutils go automake autoconf make gcc libtool \
      acl-dev acl-static \
      libseccomp-dev libseccomp-static \
      libcap-dev libcap-static \
      libapparmor-dev openssl-dev openssl-libs-static \
      linux-headers
    git clone ${{LXC_CLONE_URL}} -b ${{LXC_BRANCH}}
    cd lxc
    ./autogen.sh
    ./configure --enable-static-binaries --prefix=/usr
    make -j$(grep -c processor /proc/cpuinfo) install
build:
  build_only: true
  from:
    type: built
    tag: build-env
  binds:
    - . -> /stacker-tree
  run: |
    # golang wants somewhere to put its garbage
    export HOME=/root
    export GOPATH=/stacker-tree/.build/gopath
    export LXC_VERSION=$(git -C /lxc rev-parse HEAD)

    make -C /stacker-tree/cmd/lxc-wrapper clean
    make -C /stacker-tree stacker-static
