name: "Nightly"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY_URL: localhost:5000

jobs:
  slow-tests:
    name: "slow tests"
    runs-on: ubuntu-20.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        go-version: ["1.20"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up golang ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        env:
          SLOW_TEST: true
          REGISTRY_URL: localhost:5000
          ZOT_HOST: localhost
          ZOT_PORT: 8080
        run: |
          make check
